### ISSUE TITLE
Errors when leaflet and vue2-leaflet are updated

### ISSUE THREAD

**Issue by ibadass** [Abel-Moremi/covid-info-bw#83]
Hi,

First, nice project !

Second, I need help, I want to integrate a map (France) as you did in your project with geojson, but when I update leaflet (1.7.1) and vue2-leaflet (2.6.0), I've encounter this error: 
`[Vue warn]: Error in mounted hook: "Error: Bounds are not valid."`
I tried on your project and mine, and the errors are displayed in both cases.

Could you help me please ?

Thanks,
ibadass

**Comment by ibadass** [comment]
> Hi,
> 
> First, nice project !
> 
> Second, I need help, I want to integrate a map (France) as you did in your project with geojson, but when I update leaflet (1.7.1) and vue2-leaflet (2.6.0), I've encounter this error:
> `[Vue warn]: Error in mounted hook: "Error: Bounds are not valid."`
> I tried on your project and mine, and the errors are displayed in both cases.
> 
> Could you help me please ?
> 
> Thanks,
> ibadass

**Comment by ibadass** [comment]
I found my problem, I have to put Bounds with LatLngBounds.

**Comment by Abel-Moremi** [comment]
Oh... thank you.. Happy that you found the issue
